### ISSUE TITLE
Game Sever documentation

### ISSUE THREAD

**Issue by FernFinder** [UNLV-CS472-672/2024-S-GROUP7-LifeQuest#125]
## Describe the issue

Currently this file is a little hard to understand: `Game/server.py`. Additional comments would be useful to make working with the game server easier for everyone.

## Possible Solution

Introduce some form of documentation to make understanding the file easier.

## Additional context

Not a priority but if we have some free time to spare then we can tackle this.

## Tags

#enhancement

**Comment by dusek2** [comment]
Thank you for reminding me about documentation!

Documentation added using ChatGPT

https://chat.openai.com/share/975b0d7f-c82b-4722-8f80-9b7fa39e302f

Assistance noted in code

Closes Issue https://github.com/UNLV-CS472-672/2024-S-GROUP7-LifeQuest/issues/125
