### ISSUE TITLE
Workflow.yml Can't find src Folder

### ISSUE THREAD

**Issue by thegreatzoidberg** [UNLV-CS472-672/2024-S-GROUP7-LifeQuest#18]
## Describe the issue

Workflow.yml seems to break when trying to find src folder

## To Reproduce

If applicable, steps to reproduce the behavior:
1. Go to 'Actions' button on the top of LifeQuest Github page
2. Click on the latest Workflow Run
3. In the upper right corner select 'Re-run jobs' -> 'Re-run all jobs'

## Expected behavior

The Workflow should complete, but it fails at flake8.

## Possible Solution

Update workflow.yml to clarify where the src folder is.
Changing 'src' to 'app/src' under Linting with flake8 section might work.

## Tags

bug

**Comment by dusek2** [comment]
Closed, good job.

we got coverage reporting going.
<img width="500" alt="image" src="https://github.com/UNLV-CS472-672/2024-S-GROUP7-LifeQuest/assets/74691395/e3ba73ab-542f-424f-8678-5df69e36cc63">
