### ISSUE TITLE
No Registration Page for Creating Account (Login Page)

### ISSUE THREAD

**Issue by thegreatzoidberg** [UNLV-CS472-672/2024-S-GROUP7-LifeQuest#29]
## Describe the issue

Need an Account Registration page for new users.  Should be accessed from the Login page under the username and password boxes.

## Screenshots

![Example](https://github.com/UNLV-CS472-672/2024-S-GROUP7-LifeQuest/assets/147963318/3d768e7b-00a6-42e7-9132-caa66e6bef22)

**Comment by FernFinder** [comment]
I'll try to work on this today.
