### ISSUE TITLE
Missing quiz page

### ISSUE THREAD

**Issue by Alexmc567** [UNLV-CS472-672/2024-S-GROUP7-LifeQuest#32]
## Describe the issue

No quiz page functionality is available

**Comment by thegreatzoidberg** [comment]
This is for new accounts right?

**Comment by Alexmc567** [comment]
Correct, to determine the starting percentages on the triangle. I uploaded basic functionality for the quiz page a few hours ago. There are some bugs with it that will need to be ironed out with it but wanted to upload a somewhat working version so other's can work on it if they would like.
