### ISSUE TITLE
Game test coverage not included in CI workflow

### ISSUE THREAD

**Issue by dusek2** [UNLV-CS472-672/2024-S-GROUP7-LifeQuest#36]
## Describe the issue

A clear and concise description of what the issue is.

## To Reproduce

Push or PR into repo

## Expected behavior

Game test coverage should show in our CI workflow

## Screenshots

<img width="504" alt="image" src="https://github.com/UNLV-CS472-672/2024-S-GROUP7-LifeQuest/assets/74691395/6fc3b6fa-4cd7-4446-9113-5558997ba2a0">

## Possible Solution

Edit worflow.yml

**Comment by thegreatzoidberg** [comment]
I'll try fixing this.  Wish me luck.
