### ISSUE TITLE
Add Level Progression

### ISSUE THREAD

**Issue by MoldyPotat** [UNLV-CS472-672/2024-S-GROUP7-LifeQuest#80]
## Describe the issue

We need the ability to track levels that have been completed and prevent users from skipping ahead levels.

## To Reproduce

In level select you may select any level and there is not progress tracker.

## Expected behavior

Prevent players from skipping levels.
Ex. cannot play level 2 until level 1 has been beaten.

## Tags

enhancement

**Comment by thegreatzoidberg** [comment]
We can have some kind of boolean completion array in the character class.  Have all levels be initialized as false and flip them once they beat a level.

**Comment by MoldyPotat** [comment]
Will use this array to implement progression in the level scene.

**Comment by thegreatzoidberg** [comment]
This issue was technically closed by Merge #114 since level progression was added ("_We need the ability to track levels that have been completed and prevent users from skipping ahead levels_").  I'll make a new issue regarding unlocking levels once you beat the previous one.
